# Generated by Django 4.1.1 on 2022-11-18 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
