# Generated by Django 4.1.1 on 2022-11-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments_description_comments_title_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='description',
            new_name='comment',
        ),
    ]
